name: CI/CD Pipeline with AWS ECR, Trivy Scan, and Deployment

on:
  push:
    branches:
      - main
    tags:
      - '*'  # ✅ Runs on all tag pushes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set Image Tag Version
        id: vars
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            BRANCH_NAME=$(echo "${{ github.ref_name }}" | tr '/' '-')
            TIMESTAMP=$(date +'%Y%m%d-%H%M%S')
            echo "RELEASE_VERSION=$BRANCH_NAME-$TIMESTAMP" >> $GITHUB_ENV
          fi
          echo "🟢 Image tag version: ${{ env.RELEASE_VERSION }}"

      - name: Authenticate with AWS ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Ensure ECR Repository Exists
        run: |
          if ! aws ecr describe-repositories --repository-names "${{ secrets.ECR_REPO_NAME }}" --region ${{ secrets.AWS_REGION }} >/dev/null 2>&1; then
            aws ecr create-repository --repository-name "${{ secrets.ECR_REPO_NAME }}" --region ${{ secrets.AWS_REGION }}
            echo "✅ ECR repository created successfully!"
          else
            echo "✅ ECR repository already exists."
          fi

      - name: Build Docker Image
        run: |
          IMAGE_TAG=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPO_NAME }}:${{ env.RELEASE_VERSION }}
          LATEST_TAG=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPO_NAME }}:latest
          
          echo "🚀 Building Docker Image with tags: $IMAGE_TAG and $LATEST_TAG"
          docker build -t "$IMAGE_TAG" .
          docker tag "$IMAGE_TAG" "$LATEST_TAG"

      - name: Run Trivy Scan Before Pushing
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPO_NAME }}:${{ env.RELEASE_VERSION }}"
          format: "table"
          exit-code: "0"  # ✅ Ensures build does not fail due to vulnerabilities
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"

      - name: Push Docker Image to AWS ECR
        run: |
          IMAGE_TAG=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPO_NAME }}:${{ env.RELEASE_VERSION }}
          LATEST_TAG=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPO_NAME }}:latest
          
          echo "📤 Pushing Docker Image: $IMAGE_TAG"
          docker push "$IMAGE_TAG"

          echo "📤 Tagging and Pushing Latest Image: $LATEST_TAG"
          docker push "$LATEST_TAG"

      - name: Check tag version
        run: | 
          echo "Final Release Version: ${{ env.RELEASE_VERSION }}"
