name: CI/CD Pipeline with AWS ECR, Trivy Scan, and Deployment

on:
  push:
    branches:
      - main
    tags:
      - '*'  # ✅ Fixed: Combined tags inside push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Authenticate with AWS ECR (Using GitHub Action)
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set Image Tag Version
        id: vars
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            BRANCH_NAME=$(echo "${{ github.ref_name }}" | tr '/' '-')
            TIMESTAMP=$(date +'%Y%m%d-%H%M%S')
            echo "RELEASE_VERSION=$BRANCH_NAME-$TIMESTAMP" >> $GITHUB_ENV
          fi
          echo "Release Version: ${{ env.RELEASE_VERSION }}"

      - name: Ensure ECR Repository Exists
        run: |
          if ! aws ecr describe-repositories --repository-names "${{ secrets.ECR_REPO_NAME }}" --region ${{ secrets.AWS_REGION }} >/dev/null 2>&1; then
            aws ecr create-repository --repository-name "${{ secrets.ECR_REPO_NAME }}" --region ${{ secrets.AWS_REGION }}
            echo "ECR repository created successfully!"
          else
            echo "ECR repository already exists."
          fi

      - name: Build Docker Image
        run: |
          IMAGE_TAG=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPO_NAME }}:${{ env.RELEASE_VERSION }}
          echo "Building Docker Image with tag: $IMAGE_TAG"
          docker build -t "$IMAGE_TAG" .

      - name: Push Docker Image to AWS ECR
        run: |
          IMAGE_TAG=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPO_NAME }}:${{ env.RELEASE_VERSION }}
          echo "Pushing Docker Image: $IMAGE_TAG"
          docker push "$IMAGE_TAG"

  security_scan:
    runs-on: ubuntu-latest
    needs: build  # ✅ Trivy runs after the build job is successful
    steps:
      - name: Configure AWS Credentials for Trivy
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Authenticate with AWS ECR for Trivy Scan
        uses: aws-actions/amazon-ecr-login@v1

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPO_NAME }}:${{ env.RELEASE_VERSION }}"
          severity: "CRITICAL,HIGH"
          ignore-unfixed: true
          format: "table"

      - name: Check tag version
        run: | 
          echo "Final Release Version: ${{ env.RELEASE_VERSION }}"
